"""initial schema

Revision ID: e088c69609d2
Revises: 
Create Date: 2026-09-12 22:27:50.697690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e088c69609d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gas_level', sa.Float(), nullable=False),
    sa.Column('aqi', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('noise_db', sa.Float(), nullable=False),
    sa.Column('dust_pm', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('simulated', 'real', name='data_source'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_readings_zone'), 'environmental_readings', ['zone'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_tag_id'), 'workers', ['tag_id'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ppe_violation', 'proximity_risk', 'fire_smoke', 'environmental', 'unauthorized_zone', 'fall', name='incident_type'), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('compliant', 'warning', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('evidence_frame_path', sa.String(length=500), nullable=True),
    sa.Column('resolution_status', sa.Enum('open', 'acknowledged', 'resolved', name='resolution_status'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_resolution_status'), 'incidents', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.create_index(op.f('ix_incidents_zone'), 'incidents', ['zone'], unique=False)
    op.create_table('worker_entry_exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.Enum('entry', 'exit', name='entry_exit_direction'), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_entry_exits_direction'), 'worker_entry_exits', ['direction'], unique=False)
    op.create_index(op.f('ix_worker_entry_exits_worker_id'), 'worker_entry_exits', ['worker_id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('recipient_role', sa.String(length=80), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_incident_id'), 'alert_logs', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_incident_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_worker_entry_exits_worker_id'), table_name='worker_entry_exits')
    op.drop_index(op.f('ix_worker_entry_exits_direction'), table_name='worker_entry_exits')
    op.drop_table('worker_entry_exits')
    op.drop_index(op.f('ix_incidents_zone'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolution_status'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_workers_tag_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_environmental_readings_zone'), table_name='environmental_readings')
    op.drop_table('environmental_readings')
    # ### end Alembic commands ###